export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  GET_ALL_USERS_REQUEST: "GET_ALL_USERS_REQUEST",
  GET_ALL_USERS_FAILURE: "GET_ALL_USERS_FAILURE",
  GET_ALL_USERS_SUCCESS:"GET_ALL_USERS_SUCCESS",
};

export const userConstants = {
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  DELETE_REQUEST: "DELETE_REQUEST",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAILURE: "DELETE_FAILURE",
};

export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
};

export const articleConstants = {
  GET_ALL_ARTICLE_REQUEST: "GET_ALL_ARTICLE_REQUEST",
  GET_ALL_ARTICLE_SUCCESS: "GET_ALL_ARTICLE_SUCCESS",
  GET_ALL_ARTICLE_FAILURE: "GET_ALL_ARTICLE_FAILURE",
  ADD_NEW_ARTICLE_REQUEST: "ADD_NEW_ARTICLE_REQUEST",
  ADD_NEW_ARTICLE_SUCCESS: "ADD_NEW_ARTICLE_SUCCESS",
  ADD_NEW_ARTICLE_FAILURE: "ADD_NEW_ARTICLE_FAILURE",
};